language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t shijujohn1093/docker-frontend -f Dockerfile.dev .


script:
  - docker run -e CI=true shijujohn1093/docker-frontend npm run test -- --coverage


deploy:
  provider: elastickboanstalk
  region: "us-east-2"
  app: "docker-frontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-521930490696"
  bucket_path: "docker-frontend"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master